### ISSUE TITLE
Forgot to include mention qscintilla module being a dependency.

### ISSUE THREAD

**Issue by M4cs** [morten1982/crossCobra#2]
Without installing qsintilla via pip: `pip install qscintella` you will get the error:
```
  File "crosscobra.py", line 12, in <module>
    from PyQt5.Qsci import QsciPrinter
ModuleNotFoundError: No module named 'PyQt5.Qsci'```

**Comment by mariomakdis** [comment]
I've already added this to the [PR](https://github.com/morten1982/crossCobra/pull/1/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9).

**Comment by M4cs** [comment]
Didnt see that
